config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :boxes do

      resource :box_expert

      resources :imagecovers do
        collection do
          post :update_positions
        end
      end
    end
  end
end

app/models/spree/backend_configuration_decorator.rb
module Spree
  
  BackendConfiguration.const_set( :BOX_TABS, [ :boxes, :box_expert, :imagecovers ])
  
  BackendConfiguration.class_eval do
    
  end
  
end

app/controllers/spree/admin/box_experts_controller.rb
module Spree
  module Admin
    class BoxExpertsController < ResourceController
      #belongs_to 'spree/product', :find_by => :slug
      before_action :load_data
      #update.before :set_viewable

      def model_class
        Bm::Expert
      end

      def model_name
        "expert"
      end

      def controller_name
        "expert"
      end

      def show
        redirect_to :action => :edit
      end

      def update
        @expert.avatar.alt = params[:expert][:avatar_attributes][:alt]
        invoke_callbacks(:update, :before)

        if @expert.update_attributes(expert_params)
          invoke_callbacks(:update, :after)
          flash[:success] = flash_message_for(@expert, :successfully_updated)
          respond_with(@expert) do |format|
            format.html { redirect_to location_after_save }
            format.js   { render :layout => false }
          end
        else
          invoke_callbacks(:update, :fails)
          respond_with(@expert) do |format|
            format.html do
              flash.now[:error] = @expert.errors.full_messages.join(", ")
              render action: 'edit'
            end
            format.js { render layout: false }
          end
        end
      end

      def location_after_save
        admin_box_box_expert_url
      end

      def load_resource
      # if member_action?
      #   @object ||= load_resource_instance

      #   # call authorize! a third time (called twice already in Admin::BaseController)
      #   # this time we pass the actual instance so fine-grained abilities can control
      #   # access to individual records, not just entire models.
      #   authorize! action, @object

      #   instance_variable_set("@#{object_name}", @object)
      # else
      #   @collection ||= collection

      #   # note: we don't call authorize here as the collection method should use
      #   # CanCan's accessible_by method to restrict the actual records returned

      #   instance_variable_set("@#{controller_name}", @collection)
      # end
    end

      def load_data

        # puts "TTTTTTTTTTTTTTTTTTTTTT", collection_url
        @box = Bm::Box.find(params[:box_id])

        if @box.expert.nil?
          #build new expert
          @expert = @box.build_expert
          #save to get id
          @expert.save

          #get id from expert
          @box.bm_expert_id = @expert.id
          #save box
          @box.save
        end

        @expert = @box.expert

        if !@expert.avatar.present?
          @expert.build_avatar
        # else
        end

        # end
        # # image
        # @avatar = @object.avatars
        # if @object.avatars.nil?
        #   puts "BUILDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD <===="
        #   @avatar = @object.avatars.build
        # end

      end

      def expert_params
        params.require(:expert).permit(:name, :title, :comment, avatar_attributes: [:attachment, :alt, :viewable_id, :id])
      end
    end
  end
end

app/controllers/spree/admin/boxes_controller.rb
module Spree
  module Admin
    class BoxesController < ResourceController
      before_action :load_data, except: :index

      def model_class
        Bm::Box
      end
      
      def show
        redirect_to action: :edit
      end

      def load_data
        @expert_articles = Bm::Expert.all
        @difficulties = Bm::Difficulty.all
        @time_cooks = (0..4).step(0.5)
      end

      def location_after_save
        edit_admin_box_url(@box)
      end
    end
  end
end

app/controllers/spree/admin/imageavatars_controller.rb
module Spree
  module Admin
    class ImageavatarsController < ResourceController
      before_action :load_data

      create.before :set_viewable
      update.before :set_viewable

      def model_class
        Bm::Imageavatar
      end

      def edit
      end

      def new
        @imageavatar = @expert.avatars.build
        render :layout => false 
      end

      private 
        def location_after_destroy
          admin_expert_imageavatars_url(@expert)
        end

        def location_after_save
          admin_expert_imageavatars_url(@expert)
        end

        def load_data
          @expert = Bm::Expert.find(params[:expert_id])
        end

        def set_viewable
          @imageavatar.viewable_type = 'Bm::Expert'
          @imageavatar.viewable_id = params[:viewable_id]
        end
    end
  end
end

app/controllers/spree/admin/imagecovers_controller.rb
module Spree
  module Admin
    class ImagecoversController < ResourceController
      before_action :load_data

      create.before :set_viewable
      update.before :set_viewable

      def model_class
        Bm::Imagecover
      end

      def edit
      end

      def new
        @imagecover = @box.covers.build
        render :layout => false 
      end

      private 
        def location_after_destroy
          admin_box_imagecovers_url(@box)
        end

        def location_after_save
          admin_box_imagecovers_url(@box)
        end

        def load_data
          @box = Bm::Box.find(params[:box_id])
        end

        def set_viewable
          @imagecover.viewable_type = 'Bm::Box'
          @imagecover.viewable_id = params[:imagecover][:viewable_id]
        end
    end
  end
end

app/views/spree/admin/box_experts/_imageavatar_fields.erb
<div data-hook="admin_image_form_fields" id="<%= dom_id(f.object) %>">
  <div data-hook="thumbnail" class="field alpha four columns align-center">
    <%= f.label Spree.t(:thumbnail) %><br>
    <%= image_tag @expert.avatar.attachment.url(:normal) %>
  </div>
  <div data-hook="file" class="field four columns">
    <%= f.label :attachment, Spree.t(:filename) %><br>
    <%= f.file_field :attachment, name: "expert[avatar_attributes][attachment]", accept: 'image/png,image/gif,image/jpeg' %>
  </div>
  <div data-hook="alt_text" class="field omega four columns">
    <%= f.label :alt, Spree.t(:alt_text) %><br>
    <%= f.text_area :alt, name: "expert[avatar_attributes][alt]", rows: 4, class: 'fullwidth' %>
  </div>
  <div data-hook="expert_id" class="field">
    <%= f.hidden_field :viewable_id, name: "expert[avatar_attributes][viewable_id]", :value => @expert.id %><br>
    <%= f.hidden_field :id, name: "expert[avatar_attributes][id]", :value => @expert.avatar.try(:id) %><br>
  </div>
</div>

<div class="clear"></div>

app/views/spree/admin/box_experts/edit.html.erb
<%= render :partial => 'spree/admin/shared/box_tabs', :locals => { :current => 'Experts' } %>

<%= form_for @expert, :url => { :action => :update }, :html => {:method => :put, :id => "edit_expert", :multipart => true} do |f| %>

  <fieldset data-hook="edit-expert">
    <legend><%= Spree.t(:article) %></legend>
    <div data-hook="new_expert_attrs" class="row">
    <div class="alpha six columns">
      <%= f.label :name, Spree.t(:expert_name)%>
      <%= f.text_field :name, name: "expert[name]", :class => 'fullwidth title'%>
    </div>

    <div class="omega six columns">
      <%= f.label :title, Spree.t(:title)%>
      <%= f.text_field :title, name: "expert[title]", :class => 'fullwidth title'%>
    </div>

    <div class="alpha twelve columns">
      <%= f.label :comment, Spree.t(:comment)%>
      <%= f.text_area :comment, name: "expert[comment]", :class => 'fullwidth title', :rows => "10"%>
    </div>

    <div class="clear"></div>

    <%= f.fields_for :avatar, :include_id => false, :input_html => { :class => "update_image"} do |ff| %>
      <fieldset data-hook="edit-avatar">
        <legend><%= Spree.t(:avatar) %></legend>
        <%= render "imageavatar_fields", :f => ff %>
      </fieldset>
    <% end %>

    <div class="clear"></div>

    <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button Spree.t('actions.update'), 'ok' %>
        <span class="or"><%= Spree.t(:or) %></span>
        <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), admin_box_box_expert_url, :class => 'button' %>
    </div>

    <div class="clear"></div>

  </fieldset>
<% end %>

app/views/spree/admin/boxes/_add_dish.html.erb
<%= render :partial => "spree/admin/boxes/autocomplete", :formats => :js %>
<%= render :partial => "spree/admin/boxes/autocomplete_stock", :formats => :js %>

<div id="add-dish" data-hook>
  <fieldset class="no-border-bottom">
    <legend align="center"><%= Spree.t(:add_dish) %></legend>

    <div data-hook="add_dish_name" class="field twelve columns alpha">
      <%= label_tag :add_dish_id, Spree.t(:name_of_dish) %>
      <%= hidden_field_tag :add_dish_id, "", :class => "dish_autocomplete fullwidth" %>
      <%= hidden_field_tag :add_box_id, @box.id, :class => "box_autocomplete fullwidth" %>
    </div>

  </fieldset>

  <div id="stock_details"></div>
</div>

app/views/spree/admin/boxes/_add_line_item.html.erb
<%= render :partial => "spree/admin/boxes/autocomplete", :formats => :js %>
<%= render :partial => "spree/admin/boxes/autocomplete_line_items_stock", :formats => :js %>


<div id="add-line-item" data-hook>
  <fieldset class="no-border-bottom">
    <legend align="center"><%= Spree.t(:add_dish) %></legend>

    <div data-hook="add_product_name" class="field twelve columns alpha">
      <%= label_tag :add_line_item_dish_id, Spree.t(:name_or_sku) %>
      <%= hidden_field_tag :add_line_item_dish_id, "", :class => "dish_autocomplete fullwidth" %>
    </div>

  </fieldset>

  <div id="stock_details"></div>
</div>

app/views/spree/admin/boxes/_autocomplete.js.erb
<script type='text/template' id='dish_autocomplete_template'>
  <div class='variant-autocomplete-item'>
    <figure class='variant-image'>
      {{#if product.image }}
        <img src='{{product.image}}' />
      {{ else }}
        <img src='<%= image_path("noimage/mini.png") %>' />
      {{/if}}
    </figure>

    <div class='variant-details'>

      <h6 class="variant-name">{{product.name}}</h6>

      {{#if product.option_values}}
        {{#each product.option_values}}
          <strong>{{this.option_type_presentation}}:</strong> {{this.presentation}}<br>
        {{/each}}
      {{/if}}

    </div>
  </div>
</script>

app/views/spree/admin/boxes/_autocomplete_line_items_stock.js.erb
<script type='text/template' id='dish_line_items_autocomplete_stock_template'>
  <fieldset>
    <legend align="center"><%= Spree.t(:select_stock) %></legend>
    <table class="stock-levels" data-hook="stock-levels">
      <colgroup>
        <col style="width: 30%;" />
        <col style="width: 40%;" />
        <col style="width: 30%;" />
      </colgroup>
      <thead>
        <th><%= Spree.t(:name) %></th>
        <th><%= Spree.t(:count_on_hand) %></th>
        <th><%= Spree.t(:quantity) %></th>
        <th class="actions"></th>
      </thead>
      <tbody>
        <tr>
          <td>{{product.name}}</td>
          {{#unless product.track_inventory}}
            <td>
            It doesnt track inventory
            </td>
            <td>
              <input class="quantity" id="product_quantity" data-product-id="{{product.id}}" type="number" min="1" value="1">
            </td>
            <td class="actions">
              <button class="add_product no-text fa fa-plus icon_link with-tip" data-product-id="{{this.product_id}}" title="<%= Spree.t(:add) %>" data-action="add"></button>
            </td>
          {{else}}
            {{#if product.total_on_hand}}
              <td>
                {{product.total_on_hand}}
              </td>
              <td>
                <input class="quantity" id="product_quantity" data-product-id="{{product.id}}" type="number" min="1" value="1">
              </td>
              <td class="actions">
                <button class="add_product no-text fa fa-plus icon_link with-tip" data-product-id="{{product.id}}" title="<%= Spree.t(:add) %>" data-action="add"></button>
              </td>
            {{else}}
              <td><%= Spree.t(:out_of_stock) %></td>
              <td>0</td>
            {{/if}}
          {{/unless}}
        </tr>
      </tbody>
    </table>
  </fieldset>
</script>

app/views/spree/admin/boxes/_autocomplete_stock.js.erb
<script type='text/template' id='dish_autocomplete_stock_template'>
  <fieldset>
    <legend align="center"><%= Spree.t(:select_confirm) %></legend>
      <table class="stock-levels" data-hook="stock-levels">
        <colgroup>
          <col style="width: 20%;" />
          <col style="width: 40%;" />
          <col style="width: 20%;" />
          <col style="width: 10%;" />
          <col style="width: 10%;" />
        </colgroup>
        <thead>
          <th><%= Spree.t(:image) %></th>
          <th><%= Spree.t(:name) %></th>
          <th><%= Spree.t(:type) %></th>
          <th><%= Spree.t(:price) %></th>
          <th class="actions"></th>
        </thead>
        <tbody>
          <td class="align-center">
            <img src={{ product.image }} >
          </td>
          <td class="align-center">{{ product.name }}</td>
          <td class="align-center">{{ product.dish_type }}</td>
          <td class="align-center">{{ product.cost_price }}</td>
          <td class="actions">
            <button class="add_dish no-text fa fa-plus icon_link with-tip" data-stock-location-id="{{this.stock_location_id}}" title="<%= Spree.t(:add) %>" data-action="add"></button>
          </td>
        </tbody>
      </table>
  </fieldset>
</script>

app/views/spree/admin/boxes/_dishes.html.erb
<% if @box.products.any? %>
<div>
  <fieldset class="no-border-bottom">
    <legend align="center"><%= Spree.t(:dishes) %></legend>
    <table class="index responsive" id="listing_dishes" data-hook>
      <colgroup>
        <col style="width: 20%;" />
        <col style="width: 40%;" />
        <col style="width: 20%;" />
        <col style="width: 10%;" />
        <col style="width: 10%;" />
      </colgroup>
      <thead>
        <tr>
          <th><%= Spree.t(:image) %></th>
          <th><%= Spree.t(:name) %></th>
          <th><%= Spree.t(:type) %></th>
          <th><%= Spree.t(:price) %></th>
        </tr>
        </thead>
      <tbody>
        <% @box.products.each do |dish| %>
          <tr data-hook="admin_boxes_index_rows">
            <td class="align-center"><%= image_tag dish.master.images[0].attachment.url(:mini) %></td>
            <td class="align-center"><%= link_to dish.name, admin_product_path(dish) %></td>
            <td class="align-center"><%= dish.dish_type.name %></td>
            <td class="align-center"><%= dish.dish_price %></td>
            <td class="actions">
              <button class="remove_dish no-text fa fa-trash icon_link with-tip" data-boxdetail-id='<%= Bm::BoxDetail.where(:bm_box_id => @box.id, :spree_product_id => dish.id).first.id; %>' title="<%= Spree.t(:remove) %>" data-action="remove"></button>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </fieldset>
</div>
<% end %>

app/views/spree/admin/boxes/_form.html.erb
<legend align="center"><%= Spree.t(:box_detail) %></legend>

<%= f.hidden_field :user_id, :name => "box[spree_user_id]", :value => try_spree_current_user.id%>

<div data-hook="admin_box_form_fields">
  <div data-hook="new_box_attrs" class="left twelve columns alpha">
    <div data-hook="admin_box_name">
      <%= f.field_container :name do %>
        <%= f.label :name, Spree.t(:name) %> <span class="required">*</span><br />
        <%= f.text_field :name, name: "box[name]", :class => 'fullwidth title', :required => true %>
        <%= f.error_message_on :name %>
      <% end %>
    </div>

    <div data-hook="admin_box_story">
    <%= f.field_container :story do %>
      <%= f.label :story, Spree.t(:story)%>
      <%= f.text_area :story, name: "box[story]", :class => 'fullwidth title', :rows => "10" %>
      <%= f.error_message_on :story %>
    <% end %>
    </div>
  </div>

  <div class="clear"></div>
</div>

app/views/spree/admin/boxes/edit.html.erb
<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_boxes_list), admin_boxes_url, :icon => 'arrow-left' %></li>
<% end %>

<%= render :partial => 'spree/admin/shared/box_tabs', :locals => {:current => 'Box Details'}%>

<% if @box.products.count < 3 %>
  <%= render partial: "add_dish"%>
<% end %>

<%= render partial: "dishes"%>

<% if @box.products.count == 0 %>
  <div class="no-objects-found">
    <%= Spree.t(:your_box_is_empty)%>
  </div>
<% end %>

<%= form_for @box, method: :put, url: admin_box_url(@box), :html => { :multipart => true, :id => "new_admin_box" } do |f| %>

  <fieldset data-hook="new_box">

    <%= render partial: "form", :locals => { :f => f } %>

    <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button Spree.t('actions.update'), 'ok' %>
        <span class="or"><%= Spree.t(:or) %></span>
        <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), admin_box_url, :class => 'button' %>
    </div>
  </fieldset>
<% end %>

<div class="clear"></div>

app/views/spree/admin/boxes/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_boxes) %>
<% end %>

<% if !@boxes.any? %>
  <% content_for :page_actions do %>
    <li id="new_box_link">
      <%= button_link_to Spree.t(:new_box), new_admin_box_url, { :remote => true, :icon => 'plus', :id => 'admin_new_box' } %>
    </li>
  <% end if can?(:create, Bm::Box) %>
<% end %>

<div id="new_box_wrapper" data-hook></div>
<div class="clear"></div>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% if @boxes.any? %>
	<table class="index responsive" id="listing_orders" data-hook>
    <colgroup>
      <col style="width: 20%;" />
      <col style="width: 50%;" />
      <col style="width: 20%;" />
      <col style="width: 10%;" />
    </colgroup>
		<thead>
      <tr>
      	<th><%= Spree.t(:image_cover) %></th>
      	<th><%= Spree.t(:name) %></th>
      	<th><%= Spree.t(:dish_count) %></th>
  		</tr>
      </thead>
    <tbody>
    	<% @boxes.each do |box| %>
    		<tr data-hook="admin_boxes_index_rows">
          <% if box.covers.any? %>
    			  <td class="align-center"><%= image_tag box.covers.first.attachment.url(:normal) %></td>
          <% else %>
            <td class="align-center"><%= image_tag box.covers.build.attachment.url(:normal) %></td>
          <% end %>
    			<td class="align-center"><%= link_to box.name, admin_box_path(box) %></td>
    			<td class="align-center"><%= box.products.count %></td>
          <td class="actions" data-hook="admin_products_index_row_actions">
            <%= link_to_edit box, :no_text => true, :class => 'edit' if can?(:edit, box) && !box.deleted? %>
            &nbsp;
            <%= link_to_delete box, :no_text => true if can?(:delete, box) && !box.deleted? %>
          </td>
			  </tr>
    	<% end %>
    </tbody>
	<table>
<% else %>
	<div class="alpha sixteen columns no-objects-found">
    <%= Spree.t(:no_box_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/order')) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_box_path %>!
  </div>
<% end %>


<script>
  //Override 

  console.log("OK");
   
  $('.delete-resource').unbind('click').click( function() {
    console.log("Override");
    var el = $(this);
    if (confirm(el.data("confirm"))) {
      $.ajax({
        type: 'POST',
        url: $(this).prop("href"),
        data: {
          _method: 'delete',
          authenticity_token: AUTH_TOKEN
        },
        dataType: 'script',
        success: function(response) {
          el.parents("tr").fadeOut('hide', function() {
            $(this).remove();
            window.location.reload();
          });
        },
        error: function(response, textStatus, errorThrown) {
          show_flash('error', response.responseText);
        }
      });
    }
    return false;
  });
</script>

app/views/spree/admin/boxes/index.js.erb
//Override 

console.log("OK");
 
$('.delete-resource').unbind('click').click( function() {
  console.log("Override");
  var el = $(this);
  if (confirm(el.data("confirm"))) {
    $.ajax({
      type: 'POST',
      url: $(this).prop("href"),
      data: {
        _method: 'delete',
        authenticity_token: AUTH_TOKEN
      },
      dataType: 'script',
      success: function(response) {
        el.parents("tr").fadeOut('hide', function() {
          $(this).remove();
          window.location.reload();
        });
      },
      error: function(response, textStatus, errorThrown) {
        show_flash('error', response.responseText);
      }
    });
  }
  return false;
});

app/views/spree/admin/boxes/new.html.erb
<%= form_for @box, method: :post, url: admin_boxes_url(@box), :html => { :multipart => true, :id => "new_admin_box" } do |f| %>

  <%= f.hidden_field :user_id, :name => "box[spree_user_id]", :value => try_spree_current_user.id%>

  <div data-hook="admin_box_form_fields">
    <div data-hook="new_box_attrs" class="left sixteen columns alpha">
      <div data-hook="admin_box_name">
        <%= f.field_container :name do %>
          <%= f.label :name, Spree.t(:name) %> <span class="required">*</span><br />
          <%= f.text_field :name, name: "box[name]", :class => 'fullwidth title', :required => true %>
          <%= f.error_message_on :name %>
        <% end %>
      </div>

      <div data-hook="admin_box_story">
      <%= f.field_container :story do %>
        <%= f.label :story, Spree.t(:story)%>
        <%= f.text_area :story, name: "box[story]", :class => 'fullwidth title', :rows => "10" %>
        <%= f.error_message_on :story %>
      <% end %>
      </div>
    </div>

    <div class="clear"></div>
  </div>

  <%= render :partial => 'spree/admin/shared/new_box_links' %>

  </fieldset>
<% end %>

<script type="text/javascript">
// //<![CDATA[
//   (function($){
//     var base_url = "<%= admin_prototypes_url %>";
//     var prototype_select = $('#product_prototype_id');
//     prototype_select.change(function() {
//       var id = prototype_select.val();
//       if (id.length) {
//         var url = new Uri(base_url);
//         url.setPath(url.path() + '/' + id);
//         $('#product-from-prototype').load(url.toString());
//       } else {
//         $('#product-from-prototype').empty();
//       }
//     })
//     if (prototype_select.html() == "") {
//       prototype_select.change();
//     }
//   })(jQuery);
// //]]>
</script>

app/views/spree/admin/boxes/new.js.erb
$("#new_box_wrapper").html('<%= escape_javascript(render :template => "spree/admin/boxes/new", :formats => [:html], :handlers => [:erb]) %>');
handle_date_picker_fields();
<% unless Rails.env.test? %>
  $('.select2').select2();
<% end %>
$("#table-filter").hide();
$("#admin_new_box").parent().hide();

app/views/spree/admin/imageavatars/_form.html.erb
<div data-hook="admin_image_form_fields">
  <div class="four columns alpha">
    <div data-hook="file" class="field">
      <%= f.label :attachment, Spree.t(:filename) %><br>
      <%= f.file_field :attachment, name: "imageavatar[attachment]", accept: 'image/png,image/gif,image/jpeg' %>
    </div>
    <div data-hook="variant" class="field">
      <%= f.hidden_field :viewable_id, name: "imageavatar[viewable_id]", :value => @imageavatar.viewable_id %><br>
    </div>
  </div>
  <div data-hook="alt_text" class="field omega five columns">
    <%= f.label :alt, Spree.t(:alt_text) %><br>
    <%= f.text_area :alt, rows: 4, class: 'fullwidth' %>
  </div>
</div>

<div class="clear"></div>

app/views/spree/admin/imagecovers/edit.html.erb
<%= render :partial => 'spree/admin/shared/box_tabs', :locals => {:current => 'Images'}%>

<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_images_list), admin_box_imagecovers_url(@box), :icon => 'arrow-left' %></li>
<% end %>

<%= form_for [@box, @imagecover], url: admin_box_imagecover_url, :html => { :multipart => true } do |f| %>
  <fieldset data-hook="edit_image">
    <legend align="center"><%= @imagecover.attachment_file_name%></legend>
    <div data-hook="thumbnail" class="field alpha three columns align-center">
      <%= f.label Spree.t(:thumbnail) %><br>
      <%= link_to image_tag(@imagecover.attachment.url(:mini)), @imagecover.attachment.url(:box) %>
    </div>
    <div class="nine columns omega">
      <%= render :partial => 'form', :locals => { :f => f } %>  
    </div>
    <div class="clear"></div>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'refresh' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= link_to Spree.t('actions.cancel'), admin_box_imagecovers_url(@box), :id => 'cancel_link', :class => 'button remove' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/imagecovers/index.html.erb
<%= render :partial => 'spree/admin/shared/box_tabs', :locals => {:current => 'Images'}%>

<!--Button add new image-->
<% content_for :page_actions do %>
  <% if !@box.covers.any? %>
    <li><%= link_to_with_icon('plus', Spree.t(:new_image), new_admin_box_imagecover_url(@box), :id => 'new_image_link', :class => 'button') %></li>
  <% else %>
    <li></li>
  <% end %>
<% end %>


<div id="images" data-hook></div>

<!--Display images-->
<% unless @box.covers.any? %>
  <div class="no-objects-found">
    <%= Spree.t(:no_images_found) %>.
  </div>
<% else %>
  <table data-hook="images_table"%>
    <thead>
      <tr data-hook="images_header">
        <th colspan="2"><%= Spree.t(:thumbnail) %></th>
        <th><%= Spree.t(:alt_text) %></th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% (@box.covers).each do |image| %>
        <tr id="<%= spree_dom_id image %>" data-hook="images_row" class="<%= cycle('odd', 'even')%>">
          <td class="no-border">
            <span class="handle"></span>
          </td>
          <td>
            <%= link_to image_tag(image.attachment.url(:mini)), image.attachment.url(:normal) %>
          </td>

          <td><%= image.alt %></td>
          <td class="actions">
            <%= link_to_with_icon 'edit', Spree.t(:edit), edit_admin_box_imagecover_url(@box, image), :no_text => true, :data => {:action => 'edit'} %>
            <%= link_to_delete image, { :url => admin_box_imagecover_url(@box, image), :no_text => true } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/shared/_new_box_links.html.erb
<div class="form-buttons filter-actions actions" data-hook="buttons">
  <%= button Spree.t('actions.create'), 'ok' %>
  <span class="or"><%= Spree.t(:or) %></span>
  <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), new_admin_box_url, :class => 'button' %>
</div>

app/views/spree/admin/shared/_new_expert_links.html.erb
<div class="form-buttons filter-actions actions" data-hook="buttons">
  <%= button Spree.t('actions.create'), 'ok' %>
  <span class="or"><%= Spree.t(:or) %></span>
  <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), new_admin_expert_url, :class => 'button' %>
</div>